name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-06"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjdmMGZlNDItMDIxMy00YWY4LWE1MzMtZWI5NmExNjhhZDliIiwidGVuYW50X2lkIjoiOWNkNGZlNWFiNDVhYTU1ZjJiNTVmMjJmODQwZTIzYjg4YjUzNzhjMjcxODY4NzcwNGZiMmJlOWI4ZTU5NTU1MCIsImludGVybmFsX3NlY3JldCI6IjQ4ZmRmMjU3LTlmMGItNGNmYS04NzM0LThjNTNlMjNlNzBlZCJ9.fAoAyV_DX9od5V2ze4kk6C0W7SaiXVsNKf3lCvBxNDI"

JWT_SECRET="samarth-secret-keys"

NODE_ENV="development"

CLOUDINARY_CLOUD_NAME="dn64adr8h"
CLOUDINARY_API_KEY="751452137535974"
CLOUDINARY_API_SECRET="Vl4H2-xOozdRLKuduo451JqMM_Q"